models:
  - model.enzh.intgemm.alphas.bin
vocabs:
  - srcvocab.enzh.spm
  - trgvocab.enzh.spm
shortlist:
  - lex.50.50.enzh.s2t.bin
ssplit-mode: paragraph
max-length-break: 128
mini-batch-words: 1024
alignment: soft
max-length-factor: 2.0
