models:
  - model.jaen.intgemm.alphas.bin
vocabs:
  - vocab.jaen.spm
  - vocab.jaen.spm
shortlist:
  - lex.50.50.jaen.s2t.bin
ssplit-mode: paragraph
max-length-break: 128
mini-batch-words: 1024
alignment: soft
max-length-factor: 2.0
